# Use the official Fly base image
FROM flyio/flyctl:latest AS fly

# Build stage
FROM gradle:8.1.1-jdk17 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the Gradle configuration files
COPY build.gradle .
COPY settings.gradle .

# Copy the source code
COPY src ./src

# Build the application
RUN gradle build -x test

# Runtime stage
FROM openjdk:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file from the previous stage with the desired name
COPY --from=build /app/build/libs/vouched-1.0.0.jar ./vouched.jar

# Expose the application port
EXPOSE 8001

# Define the command to run the application
CMD ["java", "-jar", "-Dspring.profiles.active=dev", "vouched.jar"]

