# fly.toml app configuration file generated for vouched on 2023-05-18T21:16:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vouched"
primary_region = "bos"

[env]
  DOCKER_BUILDKIT = "0"

[build]
  dockerfile = "Dockerfile.dev"

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false # true if you want fly to stop idle instances.
  auto_start_machines = false

  [[services.ports]]
    handlers = ["tls"]
    start_port = 8001
    end_port = 8001

