<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Endorsement received!</title>
</head>
<body>

<div>

    <h2>
        To ${receiverName},
    </h2>

    <p>
      You have a new endorsement from ${endorserName} on your profile! Go to you profile page to publish or reject the endorsement.
    </p>

    <p>${endorserName} says: ${endorsement}</p>

    <p>
    <a href="${profileUrl}">Go to your profile</a>
    </p>

    <p>Thank you!</p>

</div>

</body>
</html>
