<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Invitation</title>
</head>
<body>

<div>

    <h2>
        Dear ${inviteeName},
    </h2>

    <p>You've been invited to join Vouched (usevouched.com)!</p>

    <p>
        You have been invited by ${inviterName} to join the Vouched platform. Click the link below to complete your
        registration:
    </p>

    <p>
        <a href="${signUpLink}"
           style="display: inline-block; padding: 10px 20px; background-color: #007BFF; color: #fff; text-decoration: none; border-radius: 5px;">Complete
            Registration</a>
    </p>

    <p>Thank you!</p>

</div>

</body>
</html>
