<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Invitation</title>
</head>
<body>

<div style="max-width: 400px; margin: 0 auto; padding: 20px; font-family: Arial, sans-serif; text-align: center;">

    <h2>You've been invited to join Vouched (usevouched.com)!</h2>

    <p>
        Dear ${inviteeName},
    </p>

    <p>
        You have been invited by ${inviterName} to join the Vouched platform. Click the link below to complete your
        registration:
    </p>

    <p>
        <a href="${registrationLink}"
           style="display: inline-block; padding: 10px 20px; background-color: #007BFF; color: #fff; text-decoration: none; border-radius: 5px;">Complete
            Registration</a>
    </p>

    <p>
        If you have any questions, feel free to contact us at ${supportEmail}.
    </p>

    <p>Thank you!</p>

</div>

</body>
</html>
