<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Invitation</title>
</head>
<body>

<div>

    <h2>
    Hi there!
    </h2>

    <p>
        ${name} (${email}) requested to join the Vouched platform. Reach out or share with them this link ${signupUrl}/sign-up!
    </p>

    <p>Thank you!</p>

</div>

</body>
</html>
